export const FETCH__LIST__USER__SUCCESS = "FETCH__LIST__USER__SUCCESS";
export const FETCH__LIST__USER__FAIL = "FETCH__LIST__USER__FAIL";
export const FETCH__USER__SUCCESS = "FETCH__USER__SUCCESS";
export const FETCH__USER__FAIL = "FETCH__USER__FAIL"